name: CI – Build & SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Build + SonarCloud
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout completo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Java 11 (requisito del SonarScanner)
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      # 3. Node.js (Angular)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 4. Instalar dependencias de tu app
      - name: Install npm dependencies
        working-directory: ./proyecto
        run: npm ci

      # 5. (Opcional) Compilar tu proyecto Angular
      - name: Build Angular app
        working-directory: ./proyecto
        run: npm run build --if-present

      # 6. Ejecutar SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0 
        with:
          projectBaseDir: proyecto                  # donde está sonar-project.properties
          args: >                                       # aquí pasas cualquier parámetro extra
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}  # token de autenticación
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
